### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rawr123** [Xcesius/AutoFlaskManager#27]
Program exited with message:
 System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,Int32> PoeHUD.Hud.Health.DebuffPanelConfig.get_Frozen()'.
   at FlaskManager.FlaskManagerCore.AilmentLogic()
   at FlaskManager.FlaskManagerCore.FlaskMain()
   at FlaskManager.FlaskManagerCore.FlaskThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Using a fresh PoEHuD and Autoflask

**Comment by zaafar** [comment]
Your poehud is not fresh, this error means your poehud is old.
